version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "sample"
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=mysecretpassword
      - PGDATABASE=sample
      - PGPORT=5432
    ports:
      - '8080:8080'
