version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "sample"
    ports:
      - '5432:5432'
    volumes:
      - .docker/db/data:/var/lib/postgresql/data

